connect / as SYSDBA
set echo on
spool /u01/app/oracle/admin/HELP/create/CreateDBFiles.log
CREATE TABLESPACE "USERS" LOGGING DATAFILE '/u03/oradata/HELP/users01.dbf' SIZE 500M REUSE AUTOEXTEND ON NEXT  2M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
ALTER DATABASE DEFAULT TABLESPACE "USERS";

CREATE TABLESPACE "DATA" LOGGING DATAFILE '/u03/oradata/HELP/data01.dbf' SIZE 2000M REUSE AUTOEXTEND ON NEXT  2M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

ALTER TABLESPACE "DATA" ADD DATAFILE '/u03/oradata/HELP/data02.dbf' SIZE 2000M REUSE AUTOEXTEND ON NEXT 2M MAXSIZE 2000M;

ALTER TABLESPACE "DATA" ADD DATAFILE '/u03/oradata/HELP/data03.dbf' SIZE 2000M REUSE AUTOEXTEND ON NEXT 2M MAXSIZE 2000M;

ALTER TABLESPACE "DATA" ADD DATAFILE '/u03/oradata/HELP/data04.dbf' SIZE 2000M REUSE AUTOEXTEND ON NEXT 2M MAXSIZE 2000M;

ALTER TABLESPACE "DATA" ADD DATAFILE '/u03/oradata/HELP/data05.dbf' SIZE 2000M REUSE AUTOEXTEND ON NEXT 2M MAXSIZE 2000M;

ALTER TABLESPACE "DATA" ADD DATAFILE '/u03/oradata/HELP/data06.dbf' SIZE 2000M REUSE AUTOEXTEND ON NEXT 2M MAXSIZE 2000M;

CREATE TABLESPACE "INDX" LOGGING DATAFILE '/u04/oradata/HELP/indx01.dbf' SIZE 2000M REUSE AUTOEXTEND ON NEXT  2M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

ALTER TABLESPACE "INDX" ADD DATAFILE '/u04/oradata/HELP/indx02.dbf' SIZE 2000M REUSE AUTOEXTEND ON NEXT 2M MAXSIZE 2000M;

ALTER TABLESPACE "INDX" ADD DATAFILE '/u04/oradata/HELP/indx03.dbf' SIZE 2000M REUSE AUTOEXTEND ON NEXT 2M MAXSIZE 2000M;

CREATE TABLESPACE "BACK" LOGGING DATAFILE '/u02/oradata/HELP/back01.dbf' SIZE 500M REUSE AUTOEXTEND ON NEXT  2M MAXSIZE 500M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

spool off
exit
