CREATE SMALLFILE 
    TABLESPACE "ADQ_TABLESPACE" 
    LOGGING 
    DATAFILE 
    '/u01/app/oracle/oradata/ADQUI/ADQ_TABLESPACE.dbf' SIZE 5M
    EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  
    AUTO;