CREATE USER "ADQUISICIONES"  PROFILE "DEFAULT" 
    IDENTIFIED BY "4DQU1_C3N72AL" DEFAULT TABLESPACE "ADQ_TABLESPACE" 
    TEMPORARY TABLESPACE "TEMP" 
    ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "ADQUISICIONES";
GRANT "CONNECT" TO "ADQUISICIONES";
GRANT "DBA" TO "ADQUISICIONES";
